In [1]:
import numpy as np
arr_zeros=np.arange(1, 11, 1)
new=1
arr_zeros[5]=new
print(arr_zeros)

[ 1  2  3  4  5  1  7  8  9 10]


In [2]:
arr_h=np.arange(10, 25, 1)
print(arr_h)
dao_nguoc = np.flip(arr_h)
print(dao_nguoc)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
[24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [3]:
arr_k = np.array([1, 2, 0, 8, 2, 0, 1, 3, 0, 5, 0])
arr_1 = arr_k[arr_k != 0]
print(arr_1)


[1 2 8 2 1 3 5]


In [4]:
arr_1[-2:]=[10,20]
print(arr_1)


[ 1  2  8  2  1 10 20]


In [5]:
index = 5
new2 = 100
arr_1=np.insert(arr_1, index, new2)
print("Mảng sau khi thêm phần tử 100:",arr_1)

Mảng sau khi thêm phần tử 100: [  1   2   8   2   1 100  10  20]


In [6]:
index_delete = [0, 1, 2]
arr_1 = np.delete(arr_1, index_delete)
print(arr_1)

[  2   1 100  10  20]
