In [1]:
import numpy as np
arr = np.full((3, 3), True, dtype=bool)



In [2]:
arr_1D = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
arr_2D = arr_1D.reshape(3, 3)
arr_2D[:, [0, 2]] = arr_2D[:, [2, 0]] 

In [3]:
arr_2D[[0, 1], :] = arr_2D[[1, 0], :]

In [4]:
arr_2D = np.flip(arr_2D, axis=0) 

In [5]:
arr_2D = np.flip(arr_2D, axis=1)

In [6]:
arr_2D_null = np.array([[1, 2, 3], [np.nan, 5, 6], [7, np.nan, 9], [4, 5, 6]])
has_nan = np.isnan(arr_2D_null).any()

In [8]:
arr_2D_null[np.isnan(arr_2D_null)] = 0
print("Câu 1: Array với giá trị True:")
print(arr)

print("\nCâu 2: arr_2D sau khi chuyển cột 1 và cột 3:")
print(arr_2D)

print("\nCâu 3: arr_2D sau khi chuyển dòng 1 và dòng 2:")
print(arr_2D)

print("\nCâu 4: arr_2D sau khi đảo ngược các dòng:")
print(arr_2D)

print("\nCâu 5: arr_2D sau khi đảo ngược các cột:")
print(arr_2D)

print("\nCâu 6: Có giá trị NaN trong arr_2D_null không? ", has_nan)
print("\nCâu 7: arr_2D_null sau khi thay thế giá trị NaN bằng 0:")
print(arr_2D_null)

Câu 1: Array với giá trị True:
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]

Câu 2: arr_2D sau khi chuyển cột 1 và cột 3:
[[6 7 8]
 [0 1 2]
 [3 4 5]]

Câu 3: arr_2D sau khi chuyển dòng 1 và dòng 2:
[[6 7 8]
 [0 1 2]
 [3 4 5]]

Câu 4: arr_2D sau khi đảo ngược các dòng:
[[6 7 8]
 [0 1 2]
 [3 4 5]]

Câu 5: arr_2D sau khi đảo ngược các cột:
[[6 7 8]
 [0 1 2]
 [3 4 5]]

Câu 6: Có giá trị NaN trong arr_2D_null không?  True

Câu 7: arr_2D_null sau khi thay thế giá trị NaN bằng 0:
[[1. 2. 3.]
 [0. 5. 6.]
 [7. 0. 9.]
 [4. 5. 6.]]
